spring:
  data:
    mongodb:
      database: user_details_manager_db
      password: admin
      username: admin
      authentication-database: admin

attachment-store:
  url: postman-mock-server.com
  read-timeout: 1000ms
  connect-timeout: 1000ms
