name: Kotlin CI

on:
  pull_request:
    branches:
      - "main"

jobs:
  ktlintCheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Run ktlintCheck
      run: ./gradlew ktlintCheck

  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run tests
        run: ./gradlew clean check
        env:
          USERNAME: ${{ github.ref_name }}
          TOKEN: ${{ secrets.LIB_TOKEN }}

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

  ticketValidation:
    uses: Group-Expense-Manager/common-ci-cd/.github/workflows/jira.yml@main