name: Build and Push Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        run: |
          version=$(echo "${{ github.event.release.tag_name }}" | sed -n 's/^v//p')
          echo "::set-output name=version::$version"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.extract_version.outputs.version }}
          secrets: |
            USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            LIB_TOKEN=${{ secrets.LIB_TOKEN }}
          build-args: |
            user=${{ github.ref_name }}
            token=${{ secrets.LIB_TOKEN }}
